import React from 'react'

const Terms_and_conditions = () => {
  return (
    <div>
      <div className="min-h-screen flex items-center justify-center bg-gray-100">
      <div className="max-w-4xl w-full p-8 bg-white rounded-lg shadow-md">
        <h1 className="text-3xl font-bold mb-6">Terms and Conditions</h1>
        <p className="mb-4">
          This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
        </p>
        <p className="mb-4">
          This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of careers.padme.com, life.padme.com & blog.padme.com website.
        </p>
        <p className="mb-4">
          This Website, including all Materials present (excluding any applicable third party materials), is the property of Myntra and is copyrighted and protected by worldwide copyright laws and treaty provisions. You hereby agree to comply with all copyright laws worldwide in Your use of this Website and to prevent any unauthorized copying of the Materials.
        </p>
        <p className="mb-4">
          By accessing this website we assume you accept these terms and conditions. Do not continue to use Website Name if you do not agree to take all of the terms and conditions stated on this page.
        </p>
        <p className="mb-4">
          The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: “Client”, “You” and “Your” refers to you, the person log on this website and compliant to the Company's terms and conditions. “The Company”, “Ourselves”, “We”, “Our” and “Us”, refers to our Company. “Party”, “Parties”, or “Us”, refers to both the Client and ourselves.
        </p>
        <h2 className="text-xl font-bold mt-8 mb-4">Cookies</h2>
        <p className="mb-4">
          We employ the use of cookies. By accessing Website Name, you agreed to use cookies in agreement with the Company Name's Privacy Policy.
        </p>
        <p className="mb-4">
          Most interactive websites use cookies to let us retrieve the user's details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.
        </p>
        <h2 className="text-xl font-bold mt-8 mb-4">License</h2>
        <p className="mb-4">
          Unless otherwise stated, Company Name and/or its licensors own the intellectual property rights for all material on Website Name. All intellectual property rights are reserved. You may access this from Website Name for your own personal use subjected to restrictions set in these terms and conditions.
        </p>
        <p className="mb-4">
          You must not:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li>Republish material from Website Name</li>
          <li>Sell, rent or sub-license material from Website Name</li>
          <li>Reproduce, duplicate or copy material from Website Name</li>
          <li>Redistribute content from Website Name</li>
        </ul>
        <p className="mb-4">This Agreement shall begin on the date hereof.</p>
        {/* Add the remaining sections */}
      </div>
    </div>
    </div>
  )
}

export default Terms_and_conditions
